# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LipsumCli < Formula
  desc "Lipsum-cli is a small terminal application written in rust language it's used f"
  homepage "https://github.com/xlith/lipsum-cli"
  url "https://github.com/xlith/lipsum-cli/archive/v0.3.0.tar.gz"
  sha256 "b50bf6b7c6df37a820201e343ba899778ba1c2879e68fa2e2ac02708251b064d"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    system "cargo", "test", *std_cargo_args
  end
end
